import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterComponent from "@/components/Footer";
import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Alpha Coffee",
  description: "Generated by Kaveh Pajhouhesh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" dir="rtl">
        <body className="bg-gray-50 font-Payda dark:bg-gray-500">
          <Navbar />
          {children}
          <FooterComponent />
        </body>
        <ToastContainer />
      </html>
    </ReactQueryClientProvider>
  );
}
