import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const peyda = localFont({
  src: "../public/Assets/fonts/font-peyda/PeydaWeb-Regular.woff2",
});

export const metadata: Metadata = {
  title: "Alpha Coffee",
  description: "Generated by Kaveh Pajhouhesh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={peyda.className}>{children}</body>
    </html>
  );
}
